apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "commonlib.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http-{{ .Values.service.port }}
      port: {{ .Values.service.port }}
      targetPort: http-{{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "commonlib.selectorLabels" . | nindent 4 }}