name: CI

on:
  push:
    tags: ['v*']
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  validate:
    uses: nix-fit-org/nix-github-workflows/.github/workflows/helm-validate.yml@main

  publish:
    needs: validate
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: nix-fit-org/nix-github-workflows/.github/workflows/helm-publish.yml@main
    with:
      registry_path: helm/templates
    secrets: inherit
